
<!--
Eliminate defects:

Replicate existing TGC functionality:
  TODO: Allow the user to add an item to the cart.
  <h2>TODO: Other [Wood Meeples]</h2>
  <h2>TODO: You Might Also Like</h2>
  <h2>TODO: Games Using This</h2>
  TODO: Enable the Wish List feature.
  TODO: Insert a fontawesome gift icon (fa-gift) before the wishlist dropdown.

Add improvements:
  TODO: What can be done about the violations and other messages generated by the part video?
  TODO: Let the user select the quantity to add to cart.
  TODO: Add Color, Category, and Material info, with links to other matching parts.
  TODO: Provide dropdowns to select different colors, materials, and sizes.
-->

<template>
  <div v-show="partId">
    <h1>{{ part.properties.name}}</h1>
    <b-container>
        <b-img :src="'http:' + part.properties.preview_uri" :alt="'Photo of ' + part.properties.name" fluid />
    </b-container>
    <p>{{ part.properties.description }}</p>
    <!-- <b-embed type="iframe" aspect="16by9" allowfullscreen
           :src="'https://www.youtube.com/embed/' + part.properties.youtube_video_id"
    /> -->
    <b-button-group>
      <b-button variant="primary" @click="buyClick">
        <span class="fas fa-cart-plus"></span>
        Buy for {{ "$" + Number(part.properties.price).toFixed(2) }}
      </b-button>
      <!-- <b-dropdown text="Add to Wish List" :disabled = "true">
        <b-dropdown-item>
          New wish list
        </b-dropdown-item>
      </b-dropdown> -->
    </b-button-group>
    <template>
      <b-table
        :items="vitalsTableItems"
        :fields='[
          {key: "key", label: "Vitals"},
          {key: "value1", label: ""},
          {key: "value2", label: ""}
        ]'>
      </b-table>
    </template>
    <template>
      <b-table
        :items="priceTableItems"
        :fields='[
          {key: "range", label: "Bulk Pricing"},
          {key: "ea", label: ""}
        ]'>
      </b-table>
    </template>
    <p>Last Price Change: {{ part.properties.last_price_change === undefined ?
      "" : part.properties.last_price_change.split(" ")[0] }}</p>
  </div>
</template>

<script>
import {wing} from "../wing.vue.js";
wing.base_uri = "https://www.thegamecrafter.com";
const StaticTGC_api_key_id = "034F04B4-7329-11E8-BA7A-8BFD93A6FE1D";

export default {
  name: 'TGCPartViewer',
  props: [
    'partId'
  ],
  data: function () {
    return {
      // We can't reuse the same wing part object over and over. We have to
      // start with an empty part and replace it when the ID changes.
      part: wing.object({})
    }
  },
  watch: {
    partId: function (val) {
      this.onLoadPart();
    }
  },
  computed: {
    priceTableItems: function () {
        let partProperties = this.part.properties;
        return [
            {range: "1-9", ea: "$" + partProperties.price + " ea"},
            {range: "10-99", ea: "$" + partProperties.price_10 + " ea"},
            {range: "100-999", ea: "$" + partProperties.price_100 + " ea"},
            {range: "1000+", ea: "$" + partProperties.price_1000 + " ea"}
        ];
    },
    vitalsTableItems: function () {
        let partProperties = this.part.properties;
        return [
            {key: "Quantity in Stock", value1: partProperties.quantity, value2: ""},
            {key: "Weight", value1: Number(partProperties.weight).toFixed(2) + " oz",
                value2: ouncesToGrams(partProperties.weight)},
            {key: "Height", value1: Number(partProperties.height).toFixed(2) + " in",
                value2: inchesToMm(partProperties.height)},
            {key: "Width", value1: Number(partProperties.width).toFixed(2) + " in",
                value2: inchesToMm(partProperties.width)},
            {key: "Depth", value1: Number(partProperties.depth).toFixed(2) + " in",
                value2: inchesToMm(partProperties.depth)}
        ];
    }
  },
  methods: {
    onLoadPart: function () {
      if (this.partId) {
        this.part = wing.object ({
          with_credentials: false,
          fetch_api: "/api/part/" + this.partId
        });

        this.part.fetch();
      }
    },
    buyClick: function() {
      this.$emit("part-buy", {
        sku_id: this.part.properties.sku_id,
        quantity: 1
      })
    }
  },
  mounted() {
    this.onLoadPart();
  }
}

function ouncesToGrams(ounces) {
    // Returns a string in the format "#.## g" or an empty string.
    if (isNaN(ounces)) {
        return "";
    } else {
        return (Number(ounces) * 28.35).toFixed(2) + " g";
    }
}

function inchesToMm(inches) {
    // Returns a string in the format "#.## mm" or an empty string.
    if (isNaN(inches)) {
        return "";
    } else {
        return (Number(inches) * 25.4).toFixed(2) + " mm";
    }
}

</script>
