
<!--
  Displays some attributes of a selected product. Only set up for game
  pieces at this point, would need more customization for other kinds of
  products, such as games.

Replicate existing TGC functionality:
  <h2>TODO: Other [Wood Meeples]</h2>
  <h2>TODO: You Might Also Like</h2>
  <h2>TODO: Games Using This</h2>
  TODO: Enable the Wish List feature.
  TODO: Insert a fontawesome gift icon (fa-gift) before the wishlist dropdown.

Add improvements:
  TODO: What can be done about the violations and other messages generated by the product video?
  TODO: Let the user select the quantity to add to cart.
  TODO: Add Color, Category, and Material info, with links to other matching products.
  TODO: Provide dropdowns to select different colors, materials, and sizes.
-->

<template>
  <div>
    <h1>{{ product.properties.name}}</h1>
    <b-container>
        <b-img :src="'http:' + product.properties.preview_uri" :alt="'Photo of ' + product.properties.name" fluid />
    </b-container>
    <p v-html="product.properties.description"></p>
    <!-- TEMP: This generates a lot of noise that I don't want to look at right now. Uncomment it later.
    <b-embed type="iframe" aspect="16by9" allowfullscreen
           :src="'https://www.youtube.com/embed/' + product.properties.youtube_video_id"
    /> -->
    <b-button-group>
      <b-button variant="primary" @click="buyClick">
        <span class="fas fa-cart-plus"></span>
        Buy for {{ "$" + Number(product.properties.price).toFixed(2) }}
      </b-button>
      <!-- <b-dropdown text="Add to Wish List" :disabled = "true">
        <b-dropdown-item>
          New wish list
        </b-dropdown-item>
      </b-dropdown> -->
    </b-button-group>
    <template>
      <b-table
        :items="vitalsTableItems"
        :fields='[
          {key: "key", label: "Vitals"},
          {key: "value1", label: ""},
          {key: "value2", label: ""}
        ]'>
      </b-table>
    </template>
    <template>
      <b-table
        :items="priceTableItems"
        :fields='[
          {key: "range", label: "Bulk Pricing"},
          {key: "ea", label: ""}
        ]'>
      </b-table>
    </template>
    <p>Last Price Change: {{ product.properties.last_price_change === undefined ?
      "" : product.properties.last_price_change.split(" ")[0] }}</p>
  </div>
</template>

<script>
import {wing} from "../wing.vue.js";
wing.base_uri = "https://www.thegamecrafter.com";
const StaticTGC_api_key_id = "034F04B4-7329-11E8-BA7A-8BFD93A6FE1D";

export default {
  name: 'TGCProductViewer',
  props: [
    'productId'
  ],
  data: function () {
    return {
      // We can't reuse the same wing product object over and over. We have to
      // start with an empty product and replace it when the ID changes.
      product: wing.object({})
    }
  },
  watch: {
    productId: function (val) {
      this.onLoadproduct();
    }
  },
  computed: {
    priceTableItems: function () {
        let productProperties = this.product.properties;
        return [
            {range: "1-9", ea: "$" + productProperties.price + " ea"},
            {range: "10-99", ea: "$" + productProperties.price_10 + " ea"},
            {range: "100-999", ea: "$" + productProperties.price_100 + " ea"},
            {range: "1000+", ea: "$" + productProperties.price_1000 + " ea"}
        ];
    },
    vitalsTableItems: function () {
        let productProperties = this.product.properties;
        return [
            {key: "Quantity in Stock", value1: productProperties.quantity, value2: ""},
            {key: "Weight", value1: Number(productProperties.weight).toFixed(2) + " oz",
                value2: ouncesToGrams(productProperties.weight)},
            {key: "Height", value1: Number(productProperties.height).toFixed(2) + " in",
                value2: inchesToMm(productProperties.height)},
            {key: "Width", value1: Number(productProperties.width).toFixed(2) + " in",
                value2: inchesToMm(productProperties.width)},
            {key: "Depth", value1: Number(productProperties.depth).toFixed(2) + " in",
                value2: inchesToMm(productProperties.depth)}
        ];
    }
  },
  methods: {
    onLoadproduct: function () {
      if (this.productId) {
        this.product = wing.object ({
          with_credentials: false,
          fetch_api: "/api/sku/" + this.productId
        });

        this.product.fetch();
      }
    },
    buyClick: function() {
      this.$emit("tgc-product-buy", {
        sku_id: this.product.properties.sku_id,
        quantity: 1
      })
    }
  },
  mounted() {
    this.onLoadproduct();
  }
}

function ouncesToGrams(ounces) {
    // Returns a string in the format "#.## g" or an empty string.
    if (isNaN(ounces)) {
        return "";
    } else {
        return (Number(ounces) * 28.35).toFixed(2) + " g";
    }
}

function inchesToMm(inches) {
    // Returns a string in the format "#.## mm" or an empty string.
    if (isNaN(inches)) {
        return "";
    } else {
        return (Number(inches) * 25.4).toFixed(2) + " mm";
    }
}

</script>
